# Generated by Django 4.2.5 on 2025-05-10 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('priority', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=2, verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='相关位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '公告信息',
                'verbose_name_plural': '公告信息',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类型描述')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公告类型',
                'verbose_name_plural': '公告类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='播报内容')),
                ('broadcast_at', models.DateTimeField(auto_now_add=True, verbose_name='播报时间')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='informations.announcement', verbose_name='公告信息')),
                ('broadcast_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasted_announcements', to=settings.AUTH_USER_MODEL, verbose_name='播报者')),
            ],
            options={
                'verbose_name': '公告播报记录',
                'verbose_name_plural': '公告播报记录',
                'ordering': ['-broadcast_at'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='informations.announcementtype', verbose_name='公告类型'),
        ),
    ]
