# Generated by Django 4.2.5 on 2025-05-10 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类别描述')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '物品类别',
                'verbose_name_plural': '物品类别',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='物品名称')),
                ('description', models.TextField(verbose_name='物品描述')),
                ('lost_time', models.DateTimeField(verbose_name='丢失时间')),
                ('lost_location', models.CharField(max_length=200, verbose_name='丢失地点')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('image', models.URLField(blank=True, null=True, verbose_name='物品图片')),
                ('status', models.CharField(choices=[('lost', '寻物中'), ('found', '已找到'), ('claimed', '已认领'), ('closed', '已关闭')], default='lost', max_length=20, verbose_name='状态')),
                ('is_broadcasted', models.BooleanField(default=False, verbose_name='是否已广播')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to='items_management.itemcategory', verbose_name='物品类别')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_lost_items', to=settings.AUTH_USER_MODEL, verbose_name='报失人')),
            ],
            options={
                'verbose_name': '失物信息',
                'verbose_name_plural': '失物信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='广播内容')),
                ('broadcast_at', models.DateTimeField(auto_now_add=True, verbose_name='广播时间')),
                ('broadcast_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='广播者')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='items_management.lostitem', verbose_name='失物信息')),
            ],
            options={
                'verbose_name': '物品广播记录',
                'verbose_name_plural': '物品广播记录',
                'ordering': ['-broadcast_at'],
            },
        ),
    ]
