# Generated by Django 4.2.5 on 2025-05-10 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='位置名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='位置描述')),
                ('floor', models.IntegerField(default=1, verbose_name='楼层')),
                ('x_coordinate', models.FloatField(verbose_name='X坐标')),
                ('y_coordinate', models.FloatField(verbose_name='Y坐标')),
                ('type', models.CharField(choices=[('gate', '登机口'), ('shop', '商店'), ('restaurant', '餐厅'), ('toilet', '卫生间'), ('security', '安检口'), ('check_in', '值机柜台'), ('luggage', '行李提取处'), ('exit', '出口'), ('entrance', '入口'), ('lounge', '休息室'), ('other', '其他')], max_length=50, verbose_name='位置类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '位置信息',
                'verbose_name_plural': '位置信息',
                'ordering': ['floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='航班号')),
                ('event_name', models.CharField(max_length=100, verbose_name='事件名称')),
                ('event_type', models.CharField(choices=[('check_in', '办理登机'), ('security', '安检'), ('boarding', '登机'), ('shopping', '购物'), ('dining', '用餐'), ('resting', '休息'), ('other', '其他')], max_length=50, verbose_name='事件类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigation_management.location', verbose_name='位置')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_schedules', to=settings.AUTH_USER_MODEL, verbose_name='旅客')),
            ],
            options={
                'verbose_name': '时间安排',
                'verbose_name_plural': '时间安排',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='NavigationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('estimated_time', models.IntegerField(default=0, verbose_name='预计时间(分钟)')),
                ('distance', models.IntegerField(default=0, verbose_name='距离(米)')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_end', to='navigation_management.location', verbose_name='目标位置')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_records', to=settings.AUTH_USER_MODEL, verbose_name='旅客')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_start', to='navigation_management.location', verbose_name='起始位置')),
            ],
            options={
                'verbose_name': '导航记录',
                'verbose_name_plural': '导航记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
