# Generated by Django 4.2.5 on 2025-05-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True, verbose_name='航班号')),
                ('airline', models.CharField(max_length=100, verbose_name='航空公司')),
                ('departure_city', models.CharField(max_length=100, verbose_name='出发城市')),
                ('arrival_city', models.CharField(max_length=100, verbose_name='到达城市')),
                ('departure_airport', models.CharField(max_length=100, verbose_name='出发机场')),
                ('arrival_airport', models.CharField(max_length=100, verbose_name='到达机场')),
                ('scheduled_departure_time', models.DateTimeField(verbose_name='计划出发时间')),
                ('scheduled_arrival_time', models.DateTimeField(verbose_name='计划到达时间')),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True, verbose_name='实际出发时间')),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='实际到达时间')),
                ('gate', models.CharField(blank=True, max_length=50, null=True, verbose_name='登机口')),
                ('terminal', models.CharField(blank=True, max_length=50, null=True, verbose_name='航站楼')),
                ('status', models.CharField(choices=[('scheduled', '计划'), ('delayed', '延误'), ('boarding', '登机中'), ('departed', '已起飞'), ('arrived', '已到达'), ('cancelled', '取消')], default='scheduled', max_length=20, verbose_name='航班状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '航班',
                'verbose_name_plural': '航班',
                'ordering': ['-scheduled_departure_time'],
            },
        ),
        migrations.CreateModel(
            name='FlightAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='播报内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='播报时间')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='flight_management.flight', verbose_name='航班')),
            ],
            options={
                'verbose_name': '航班播报',
                'verbose_name_plural': '航班播报',
                'ordering': ['-created_at'],
            },
        ),
    ]
