# Generated by Django 4.2.5 on 2025-05-10 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='标签描述')),
                ('color', models.CharField(default='#409EFF', max_length=20, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '旅客标签',
                'verbose_name_plural': '旅客标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PassengerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequent_flyer_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='常旅客号码')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='护照号码')),
                ('id_card_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号码')),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='紧急联系电话')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('vip_level', models.PositiveSmallIntegerField(default=0, verbose_name='VIP等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_profile', to=settings.AUTH_USER_MODEL, verbose_name='旅客')),
                ('tags', models.ManyToManyField(blank=True, related_name='passengers', to='passenger_management.passengertag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '旅客资料',
                'verbose_name_plural': '旅客资料',
            },
        ),
        migrations.CreateModel(
            name='PassengerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='备注内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='旅客')),
            ],
            options={
                'verbose_name': '旅客备注',
                'verbose_name_plural': '旅客备注',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassengerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('profile_update', '更新个人信息'), ('flight_booking', '航班预订'), ('flight_checkin', '航班值机'), ('lost_item_report', '物品报失'), ('other', '其他')], max_length=50, verbose_name='活动类型')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='旅客')),
            ],
            options={
                'verbose_name': '旅客活动',
                'verbose_name_plural': '旅客活动',
                'ordering': ['-created_at'],
            },
        ),
    ]
